### PR TITLE
add class KSstimSeqDir

### PR DESCRIPTION
**Pull request by Zhaoxi-Liu**
Class KSstimSeqDir is similar to KSstimAllDir, while you can customize the direction sequence in which KSstim are presented.

### CODE REVIEW

**Comment by jun-wispr** [comment]
Hey, thank you for contributing to this repository. I did not know people are still using it! Looks like this class will be very useful. If you have tested it, can you merge? I do not see a `merge` button here.

**Comment by zhuangjun1981** [comment]
Hey, thank you for contributing to this repository. I did not know people are still using it! Looks like this class will be very useful. Have you tested it?

**Comment by Zhaoxi-Liu** [comment]
> Hey, thank you for contributing to this repository. I did not know people are still using it! Looks like this class will be very useful. Have you tested it?

haha，thanks a lot for your work, I'm working on mouse HVAs and your research really helps a lot! 

I have tested it and it could work, although it would take several time (about 1 min) to generate numpy sequence and others before start playing if we want 10 round * 4 directions. Maybe I'll improve it further.

**Comment by zhuangjun1981** [comment]
Yes. It is designed to run on computers with limited GPU power, so the whole sequence is generated before display other than on the fly. Merged.

**Comment by Zhaoxi-Liu** [comment]
> Yes. It is designed to run on computers with limited GPU power, so the whole sequence is generated before display other than on the fly. Merged. By the way, which institute are you in?

I am currently working on my PhD. It is a joint program between Peking University and the Chinese Institute for Brain Research, Beijing (CIBR, Beijing). Are you still doing research on the mouse visual cortex?

**Pull request merged**
